name: Docker Image CI
permissions:
  contents: read

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }}

      - name: Tag Docker image as latest (if no dash in tag)
        if: ${{ !contains(env.TAG_NAME, '-') }}
        run: docker tag ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }} ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:latest

      - name: Push Docker image to Docker Hub (latest)
        if: ${{ !contains(env.TAG_NAME, '-') }}
        run: docker push ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:latest

      - name: Push Docker image to Docker Hub (tag)
        run: docker push ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Tag Docker image for GitHub Container Registry (latest)
        if: ${{ !contains(env.TAG_NAME, '-') }}
        run: docker tag ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }} ghcr.io/${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:latest

      - name: Tag Docker image for GitHub Container Registry (tag)
        run: docker tag ${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }} ghcr.io/${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }}

      - name: Push Docker image to GitHub Container Registry (latest)
        if: ${{ !contains(env.TAG_NAME, '-') }}
        run: docker push ghcr.io/${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:latest

      - name: Push Docker image to GitHub Container Registry (tag)
        run: docker push ghcr.io/${{ env.DOCKER_USERNAME }}/ecowitt-eventbridge:${{ env.TAG_NAME }}
